name: Microservice deployment

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Select environment to deploy to"
        required: true
        type: choice
        options:
          - dev
          - test
          - prod
      microservice:
        description: "Select microservice to deploy"
        required: true
        type: choice
        options:
          - my_microservice
         #- another microservice 

env:
  TYPE: ${{ inputs.environment }}
jobs:
  deploy:
    runs-on: #TODO: add github runner here

    steps:
      - uses: actions/checkout@v2

      - name: Execute terraform init for the microservice's security
        working-directory: ./terraform/infrastructure/environments/${{inputs.type}}/${{ inputs.microservice }}_role
        run: terraform init -reconfigure

      - name: Execute terraform apply for the microservice's security
        working-directory: ./terraform/infrastructure/environments/${{inputs.type}}/${{ inputs.microservice }}_role
        run: terraform apply -auto-approve

      - name: Execute terraform init for the microservice
        working-directory: ./terraform/infrastructure/environments/${{inputs.type}}/${{ inputs.microservice }}
        run: terraform init -reconfigure

      - name: Execute terraform apply for the microservice
        working-directory: ./terraform/infrastructure/environments/${{inputs.type}}/${{ inputs.microservice }}
        run: terraform apply -target=module.${{ inputs.microservice }} -auto-approve
